apiVersion: v1
kind: ConfigMap
metadata:
  name: redash-config
  namespace: redash
data:
  PYTHONUNBUFFERED: "0"
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgres://redash:redash@postgres:5432/redash"
  REDASH_COOKIE_SECRET: "veryverysecret"
  REDASH_SECRET_KEY: "supersecretkey"
